-- CreateTable
CREATE TABLE "COMP" (
    "COMP_ID" TEXT NOT NULL,
    "COMP_COD_CNPJ" TEXT NOT NULL,
    "COMP_EMAIL" TEXT NOT NULL,
    "COMP_NAM" TEXT NOT NULL,
    "COMP_NAM_FANT" TEXT,
    "COMP_DAT_CREA" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "COMP_OBS" TEXT NOT NULL,

    CONSTRAINT "COMP_pkey" PRIMARY KEY ("COMP_ID")
);

-- CreateTable
CREATE TABLE "USER" (
    "COMP_ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "USER_EMAIL" TEXT NOT NULL,
    "USER_NAM" TEXT NOT NULL,
    "USER_COD_CPF" TEXT NOT NULL,
    "USER_NUM_CEL" INTEGER NOT NULL,
    "USER_IND_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "USER_DAT_CREA" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USER_DAT_LOGIN" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("USER_ID","COMP_ID")
);

-- CreateTable
CREATE TABLE "PUSR" (
    "COMP_ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "PUSR_IND_ADM" BOOLEAN NOT NULL,
    "PUSR_IND_INCL" BOOLEAN NOT NULL,
    "PUSR_IND_EXCL" BOOLEAN NOT NULL,
    "PUSR_IND_UPDA" BOOLEAN NOT NULL,

    CONSTRAINT "PUSR_pkey" PRIMARY KEY ("COMP_ID","USER_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "COMP_COMP_COD_CNPJ_key" ON "COMP"("COMP_COD_CNPJ");

-- CreateIndex
CREATE UNIQUE INDEX "COMP_COMP_EMAIL_key" ON "COMP"("COMP_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "USER_USER_EMAIL_key" ON "USER"("USER_EMAIL");

-- AddForeignKey
ALTER TABLE "USER" ADD CONSTRAINT "USER_COMP_ID_fkey" FOREIGN KEY ("COMP_ID") REFERENCES "COMP"("COMP_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUSR" ADD CONSTRAINT "PUSR_USER_ID_COMP_ID_fkey" FOREIGN KEY ("USER_ID", "COMP_ID") REFERENCES "USER"("USER_ID", "COMP_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
