# Generated by Django 5.0.3 on 2024-03-09 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mate_id', models.IntegerField(db_column='MATE_ID', primary_key=True, serialize=False)),
                ('mate_dsc', models.CharField(db_column='MATE_DSC', max_length=100)),
                ('mate_dat_cria', models.DateTimeField(auto_now_add=True, db_column='MATE_DAT_CRIA')),
                ('mate_dat_atua', models.DateTimeField(auto_now=True, db_column='MATE_DAT_ATUA')),
                ('mate_usr', models.ForeignKey(db_column='MATE_USR', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MATE',
            },
        ),
    ]
