# Generated by Django 5.0.3 on 2024-03-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='mate_usr',
            new_name='mate_user',
        ),
    ]
