# Generated by Django 5.0.3 on 2024-03-09 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_alter_material_mate_dat_atua_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleMaterial',
            fields=[
                ('mate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='materiais.material')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grup_id', models.AutoField(db_column='GRUP_ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_dsc', models.CharField(db_column='GRUP_DSC', max_length=100, verbose_name='Descrição')),
                ('grup_dat_cria', models.DateTimeField(auto_now_add=True, db_column='GRUP_DAT_CRIA', verbose_name='Data da Criação')),
                ('grup_dat_atua', models.DateTimeField(auto_now=True, db_column='GRUP_DAT_ATUA', verbose_name='Ultima Atualização')),
                ('grup_user', models.ForeignKey(db_column='GRUP_USR', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'GRUP',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='grup_id',
            field=models.ForeignKey(db_column='GRUP_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='materiais.grupo', verbose_name='ID Grupo'),
            preserve_default=False,
        ),
    ]
