# Generated by Django 5.0.3 on 2024-03-09 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_alter_controlematerial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlematerial',
            name='cmat_ind_ativo',
            field=models.BooleanField(db_column='CMAT_IND_ATIVO', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='controlematerial',
            name='mate_id',
            field=models.OneToOneField(db_column='MATE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='materiais.material', verbose_name='ID Material'),
        ),
    ]
