# Generated by Django 5.0.3 on 2024-03-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0007_alter_controlematerial_cmat_ind_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grup_dsc',
            field=models.CharField(db_column='GRUP_DSC', max_length=100, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mate_dsc',
            field=models.CharField(db_column='MATE_DSC', max_length=100, unique=True, verbose_name='Descrição'),
        ),
    ]
