# Generated by Django 5.0.3 on 2024-03-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0008_alter_grupo_grup_dsc_alter_material_mate_dsc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlematerial',
            old_name='user_dsc',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='user_dsc',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='user_dsc',
            new_name='user_id',
        ),
    ]
