-- AlterTable
ALTER TABLE "COMP" ALTER COLUMN "COMP_OBS" DROP NOT NULL;

-- AlterTable
ALTER TABLE "PUSR" ALTER COLUMN "PUSR_IND_ADM" DROP NOT NULL,
ALTER COLUMN "PUSR_IND_INCL" DROP NOT NULL,
ALTER COLUMN "PUSR_IND_EXCL" DROP NOT NULL,
ALTER COLUMN "PUSR_IND_UPDA" DROP NOT NULL;

-- AlterTable
ALTER TABLE "USER" ALTER COLUMN "USER_DAT_LOGIN" DROP NOT NULL;
