version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: controle-estoque
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres_data: