# Generated by Django 5.0.3 on 2024-03-10 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('coes_id', models.AutoField(db_column='COES_ID', primary_key=True, serialize=False, verbose_name='Corredor')),
                ('coes_dsc', models.CharField(db_column='COES_DSC', max_length=100, unique=True, verbose_name='Descrição')),
                ('coes_dat_cria', models.DateTimeField(auto_now_add=True, db_column='COES_DAT_CRIA', verbose_name='Data da Criação')),
                ('coes_dat_atua', models.DateTimeField(auto_now=True, db_column='COES_DAT_ATUA', verbose_name='Ultima Atualização')),
                ('user_id', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
                'db_table': 'COES',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('loes_id', models.AutoField(db_column='LOES_ID', primary_key=True, serialize=False, verbose_name='Local')),
                ('loes_dsc', models.CharField(db_column='LOES_DSC', max_length=100, unique=True, verbose_name='Descrição')),
                ('loes_dat_cria', models.DateTimeField(auto_now_add=True, db_column='LOES_DAT_CRIA', verbose_name='Data da Criação')),
                ('loes_dat_atua', models.DateTimeField(auto_now=True, db_column='LOES_DAT_ATUA', verbose_name='Ultima Atualização')),
                ('user_id', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'db_table': 'LOES',
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('poes_id', models.AutoField(db_column='POES_ID', primary_key=True, serialize=False, verbose_name='Posição')),
                ('poes_dsc', models.CharField(db_column='POES_DSC', max_length=100, unique=True, verbose_name='Descrição')),
                ('poes_dat_cria', models.DateTimeField(auto_now_add=True, db_column='POES_DAT_CRIA', verbose_name='Data da Criação')),
                ('poes_dat_atua', models.DateTimeField(auto_now=True, db_column='POES_DAT_ATUA', verbose_name='Ultima Atualização')),
                ('user_id', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'db_table': 'POES',
            },
        ),
        migrations.CreateModel(
            name='Prateleira',
            fields=[
                ('pres_id', models.AutoField(db_column='PRES_ID', primary_key=True, serialize=False, verbose_name='Prateleira')),
                ('pres_dsc', models.CharField(db_column='PRES_DSC', max_length=100, unique=True, verbose_name='Descrição')),
                ('pres_dat_cria', models.DateTimeField(auto_now_add=True, db_column='PRES_DAT_CRIA', verbose_name='Data da Criação')),
                ('pres_dat_atua', models.DateTimeField(auto_now=True, db_column='PRES_DAT_ATUA', verbose_name='Ultima Atualização')),
                ('user_id', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Prateleira',
                'verbose_name_plural': 'Prateleiras',
                'db_table': 'PRES',
            },
        ),
        migrations.CreateModel(
            name='SubLocal',
            fields=[
                ('sles_id', models.AutoField(db_column='SLES_ID', primary_key=True, serialize=False, verbose_name='Sub-Local')),
                ('sles_dsc', models.CharField(db_column='SLES_DSC', max_length=100, verbose_name='Descrição')),
                ('sles_dat_cria', models.DateTimeField(auto_now_add=True, db_column='SLES_DAT_CRIA', verbose_name='Data da Criação')),
                ('sles_dat_atua', models.DateTimeField(auto_now=True, db_column='SLES_DAT_ATUA', verbose_name='Ultima Atualização')),
                ('user_id', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sub-Local',
                'verbose_name_plural': 'Subs-Locais',
                'db_table': 'SLES',
            },
        ),
        migrations.CreateModel(
            name='Enderecamento',
            fields=[
                ('ense_id', models.AutoField(db_column='ENSE_ID', primary_key=True, serialize=False, verbose_name='Endereçamento')),
                ('enes_dat_cria', models.DateTimeField(auto_now_add=True, db_column='ENES_DAT_CRIA', verbose_name='Data da Criação')),
                ('enes_dat_atua', models.DateTimeField(auto_now=True, db_column='ENES_DAT_ATUA', verbose_name='Ultima Atualização')),
                ('coes_id', models.ForeignKey(db_column='COES_ID', on_delete=django.db.models.deletion.CASCADE, to='locais.corredor', verbose_name='Corredor')),
                ('user_id', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('loes_id', models.ForeignKey(db_column='LOES_ID', on_delete=django.db.models.deletion.CASCADE, to='locais.local', verbose_name='Local de Estoque')),
                ('poes_id', models.ForeignKey(db_column='POES_ID', on_delete=django.db.models.deletion.CASCADE, to='locais.posicao', verbose_name='Posição')),
                ('pres_id', models.ForeignKey(db_column='PRES_ID', on_delete=django.db.models.deletion.CASCADE, to='locais.prateleira', verbose_name='Prateleira')),
                ('sles_id', models.ForeignKey(db_column='SLES_ID', on_delete=django.db.models.deletion.CASCADE, to='locais.sublocal', verbose_name='Sub Local de Estoque')),
            ],
            options={
                'verbose_name': 'Endereçamento',
                'verbose_name_plural': 'Endereçamentos',
                'db_table': 'ENES',
                'unique_together': {('loes_id', 'sles_id', 'coes_id', 'pres_id', 'poes_id')},
            },
        ),
    ]
