# Generated by Django 5.0.3 on 2024-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_localmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmaterial',
            name='loma_qtd',
            field=models.FloatField(db_column='LOMA_QTD', default=1, verbose_name='Quantidade de Material'),
            preserve_default=False,
        ),
    ]
